### ISSUE TITLE
Write Dockerfile and Makefile to work with current setup

### ISSUE THREAD

**Issue by SarahAlidoost** [esciencecenter-digital-skills/workshop-template#119]

**Comment by SarahAlidoost** [comment]
@dsmits just to let you know, @jhidding is working on this issue. If you want to share ideas, please discuss them here.

**Comment by dsmits** [comment]
Docker command to run jekyll: `docker run --rm -it -p 4000:4000 -v $PWD:/srv/jekyll jekyll/jekyll:3 jekyll serve`
