### ISSUE TITLE
Consider different versions of metadata and rendered workshop pages 

### ISSUE THREAD

**Issue by SarahAlidoost** [esciencecenter-digital-skills/workshop-template#121]
GitHub action renders workshop pages using the information in workshop metadata. The metadata can be changed for different workshops. If the GitHub action of an old workshop repository is triggered somehow, it renders new information. Perhaps, we can add a date or versioning tag to GitHub action! (cc @jhidding and @mkuzak )

**Comment by jhidding** [comment]
We could trigger on release. When the final page is ready, the lead instructor can create release 1.0, and the page builds....

**Comment by SarahAlidoost** [comment]
@jhidding do you mean creating a release in https://github.com/esciencecenter-digital-skills/workshop-metadata repo?

**Comment by svenvanderburg** [comment]
I've implemented a solution in #131. Of course this does not fully solve the problem that @SarahAlidoost pointed out. It is still possible that someone creates a new release, which will still fetch the latest workshop metadata. But at least it happens consciously. 

To solve the last issue we could also add tags to the workshop-metadata, and document how users can point to a specific tag of the workshop metadata in the index.md. But, in my opinion that makes things overly complicated. Especially for a feature that will probably never be used. (who ever consciously updates an old workshop website and caring about that the syllabus might slightly change?).
