### ISSUE TITLE
Template sometimes cannot reach the metadata

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/workshop-template#134]
**Describe the bug**
When preparing for the DC workshop for geospatial Python, the template fails to link to automatically the metadata.

**To Reproduce**
1. Follow the [README ](https://github.com/esciencecenter-digital-skills/workshop-template#readme) to create a workshop `XXXX-XX-XX-dc-geospatial`
2. Use [this csv file](https://github.com/esciencecenter-digital-skills/2022-11-21-dc-geospatial/blob/main/_data/data.csv) to place the existing one in `_data` folder
3. Build the page by manually running GitHub Action
4. When finished, check the rendered page

**Expected behavior**
I was expecting the workshop page can already get the metadata fields like `introduction`, `who`, `schedule`, etc from the [metadata repo](https://github.com/esciencecenter-digital-skills/workshop-metadata) (under [dc-geospatial](https://github.com/esciencecenter-digital-skills/workshop-metadata/tree/main/dc-geospatial)), but it's not. Only the general info of `dc` is available.

**Desktop (please complete the following information):**
 - OS: WSL, Ubuntu 18.04.2
 - Browser: Chrome

**Additional context**
I am fixing this by manually providing the URL to the metadata. See [this commit](https://github.com/esciencecenter-digital-skills/2022-11-21-dc-geospatial/commit/4a6443590ac9f5a16d3d3728aed2afb99d007c61). I also see in another DC workshop the same fix is applied, see [this commit](https://github.com/esciencecenter-digital-skills/2022-05-30-dc-socsci-python-nlesc/commit/e9bee25171473a7d8da6a881279d9d46b5f32721)

I found for the[ template csv](https://github.com/esciencecenter-digital-skills/workshop-template/blob/main/_data/data.csv), it seems the template can reach the metadata.

**Comment by rogerkuou** [comment]
@svenvanderburg as discussed I added this issue here. Thx for taking care!

**Comment by svenvanderburg** [comment]
Thanks @rogerkuou! Very clear description of the issue 🙏
