### ISSUE TITLE
The embedded eventbrite registration page is very small

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/workshop-template#136]
**Describe the bug**
The space for the embedded registration form is very small, which is not super user friendly.

**To Reproduce**
1. Go to e.g. https://esciencecenter-digital-skills.github.io/2022-12-05-ds-dl-intro/ 
2. In the embedded eventbrite page, press "register"

**Expected behavior**
Might be better to just be redirected to the eventbrite page

**Screenshots**
![Selection_223](https://user-images.githubusercontent.com/131889/200839553-22f13e7a-1eb5-41f5-ad70-1cae9ec8cad0.png)

**Comment by JaroCamphuijsen** [comment]
I created a PR that only solves the first step in registration (and makes the experience somewhat better for later stages by increasing the size of the iframe. A redirect to the EventBrite page seems like a better option indeed.
