### ISSUE TITLE
Deactivate/Modify instructions for issues and pull requests

### ISSUE THREAD

**Issue by PabRod** [esciencecenter-digital-skills/workshop-template#3]
## Problem

This repository inherited the configuration from The Carpentries. When a new issue or pull request is created, their instructions appear. Most likely we want to have either none or our own instructions.

## Possible solution

Delete / edit the instructions in the _settings_ menu.

**Comment by mkuzak** [comment]
The Issue and PR templates are in the `.github` folder. Those need to be updated to reflect eScience Center Digital Skills. While updating, we should use a [new template format](https://docs.github.com/articles/about-issue-and-pull-request-templates), because it looks like we are using the old one.

**Comment by svenvanderburg** [comment]
@liekelotte @jhidding @mkuzak can one of you make me owner of this repository? I need to access the settings to be able to change this.

**Comment by mkuzak** [comment]
done
