### ISSUE TITLE
create license page

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/workshop-template#50]
copy paste carpentries file and fill out license info based on that

**Comment by mkuzak** [comment]
The License page should be based on the Carpentries.
It should be located in the escience-academy.github.io
https://escience-academy.github.io/license
Should Include a section for: the Cerpentries, Code Refinery and Digital Skills.

**Comment by SarahAlidoost** [comment]
@mkuzak please close this one after you review the license.

**Comment by svenvanderburg** [comment]
@mkuzak please close the issue.
