### ISSUE TITLE
Include data download instructions for Software Carpentry lessons

### ISSUE THREAD

**Issue by dafnevk** [esciencecenter-digital-skills/workshop-template#76]
The instructions on downloading the required datasets are not by default included in the templates from Software Caprentry.
Here I manually added them for our workshop page: https://github.com/esciencecenter-digital-skills/2021-09-06-swc-gapminder-python-nlesc/commit/6a6cc30f3d1adb19f0f324d15214741a8637082b
Maybe the files can be included in our template.

**Comment by dafnevk** [comment]
At the 2021-09-06-swc-gapminder-python-nlesc workshop, we found out that:
- Link to the shell data was incorrect, should be: http://swcarpentry.github.io/shell-novice/data/shell-lesson-data.zip
- The instructions on downloading the Python data were insufficiently clear on where to put the data. The instructions should suggest to create a directory for the workshop on the Desktop, and download and extract the data to that folder.

**Comment by SarahAlidoost** [comment]
@dafnevk I think this is an issue for SWC lesson repository.

**Comment by svenvanderburg** [comment]
I agree with @SarahAlidoost. We could now have these additional instructions in the workshop metadata, but since we do not teach software carpentry anymore we also don't have a folder in workshop-metadata. I therefore close this issue.
