### ISSUE TITLE
Include syllabus

### ISSUE THREAD

**Issue by dafnevk** [esciencecenter-digital-skills/workshop-template#77]
There is no longer a placeholder for a syllabus of the workshop in `index.md`. The syllabus also disappeared from the capentries templates. I created one for our upcoming workshop: https://github.com/esciencecenter-digital-skills/2021-09-06-swc-gapminder-python-nlesc/blob/gh-pages/_includes/swc/syllabus.html but I couldn't find a readily available syllabus for the python-gapminder lesson.

**Comment by svenvanderburg** [comment]
Whenever we teach swc-gapminder-python again we can add the syllabus to the then newly created workshop metadata, based on the most recent swc material at the time.
