### ISSUE TITLE
slug field empty in page generated for DC workshop

### ISSUE THREAD

**Issue by loostrum** [esciencecenter-digital-skills/workshop-template#97]
The slug field is there in the data.csv file, but the slug field in the generated pages is empty, see this snippet from the html:
```
<!doctype html>
<html lang="en">
  <head>

    <meta name="slug" content="" />
    <meta name="startdate" content="2021-12-06T00:00:00Z" />
```
The slug field is used in the pre- and post-workshop survey URLs, so it should be set.

**Comment by loostrum** [comment]
[Example repository in broken state](https://github.com/esciencecenter-digital-skills/2021-12-06-dc-socsci-python-nlesc/tree/882e806c1ad5a9ebb9e3422b17372e1baba1f2b3)

**Comment by SarahAlidoost** [comment]
@loostrum thanks for reporting the issue. I will work on it.
